name: shaqlawa_restaurant_menu
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  fast_cached_network_image: ^1.2.0
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  image_network: ^2.5.4+1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cat0/
    - assets/cat1/
    - assets/cat2/
    - assets/cat3/
    - assets/cat4/
    - assets/cat5/
    - assets/cat6/
    - assets/cat7/
    - assets/cat8/
    - assets/cat9/
    - assets/cat10/
    - assets/cat11/
    - assets/Categories/
    - assets/offers/
